import { useState } from 'react';
import { useSessionStore } from '../../stores/sessionStore';
import { FileText, Download, Share2 } from 'lucide-react';

export default function ReportsView() {
  const { currentSession, drivers } = useSessionStore();
  const [selectedReport, setSelectedReport] = useState<string | null>(drivers[0]?.code || null);

  if (!currentSession) {
    return (
      <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <span className="t-data" style={{ color: 'var(--txt-secondary)' }}>LOAD TELEMETRY TO INTERACT</span>
      </div>
    );
  }

  return (
    <div style={{ flex: 1, display: 'flex', background: 'var(--bg-base)', overflow: 'hidden' }}>
      
      {/* ── SIDEBAR (REPORTS LIST) ── */}
      <div style={{ width: 260, background: 'var(--bg-sidebar)', borderRight: '1px solid var(--border-mid)', display: 'flex', flexDirection: 'column' }}>
        <div style={{ padding: '20px 20px 10px', borderBottom: '1px solid var(--border-mid)' }}>
          <h2 style={{ fontSize: 14, color: 'var(--txt-white)', margin: '0 0 4px 0', letterSpacing: '0.04em' }}>AI DEBRIEFS</h2>
          <span className="t-label-xs">GENERATED BY IBM GRANITE</span>
        </div>
        
        <div style={{ flex: 1, overflowY: 'auto' }}>
          {drivers.map(d => (
            <div 
              key={d.code}
              onClick={() => setSelectedReport(d.code)}
              style={{
                padding: '12px 20px',
                borderBottom: '1px solid var(--border-soft)',
                background: selectedReport === d.code ? 'rgba(255,255,255,0.05)' : 'transparent',
                borderLeft: selectedReport === d.code ? '2px solid var(--cyan)' : '2px solid transparent',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: 12
              }}
            >
              <FileText size={16} color={selectedReport === d.code ? 'var(--cyan)' : 'var(--txt-secondary)'} />
              <div>
                <div style={{ fontSize: 13, color: selectedReport === d.code ? 'var(--txt-white)' : 'var(--txt-primary)', fontWeight: 600 }}>
                  {d.code} Strategy Debrief
                </div>
                <div className="t-label-xs" style={{ marginTop: 2 }}>{currentSession.gp_name}</div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* ── MAIN DOCUMENT PANE ── */}
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', background: 'var(--bg-base)' }}>
        {selectedReport ? (() => {
          const driverStrat = strategy?.drivers?.[selectedReport];
          
          return (
            <>
              <div style={{ padding: '20px 32px', borderBottom: '1px solid var(--border-mid)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div>
                  <h1 style={{ fontSize: 24, fontWeight: 700, color: 'var(--txt-white)', margin: '0 0 4px 0' }}>{selectedReport} Strategy Debrief</h1>
                  <span className="t-data" style={{ color: 'var(--txt-secondary)' }}>Generated after Lap {currentSession.total_laps}</span>
                </div>
                <div style={{ display: 'flex', gap: 12 }}>
                  <button style={{ padding: '8px 12px', background: 'var(--bg-panel)', border: '1px solid var(--border-soft)', borderRadius: 4, color: 'var(--txt-white)', display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer' }}>
                    <Share2 size={14} /> Share
                  </button>
                  <button style={{ padding: '8px 12px', background: 'var(--cyan)', border: 'none', borderRadius: 4, color: '#000', fontWeight: 600, display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer' }}>
                    <Download size={14} /> Export PDF
                  </button>
                </div>
              </div>

              <div style={{ flex: 1, overflowY: 'auto', padding: '32px' }}>
                <div style={{ maxWidth: 700, margin: '0 auto', color: 'var(--txt-primary)', fontSize: 14, lineHeight: 1.6, fontFamily: 'Inter' }}>
                  
                  {!driverStrat ? (
                    <div style={{ padding: 24, background: 'var(--bg-row-alt)', borderRadius: 4, textAlign: 'center' }}>
                      <span className="t-data" style={{ color: 'var(--txt-secondary)' }}>No advanced strategy data available for {selectedReport}.</span>
                    </div>
                  ) : (
                    <>
                      <h3 style={{ color: 'var(--txt-white)', marginBottom: 12 }}>Executive Summary</h3>
                      <p style={{ marginBottom: 24 }}>
                        {driverStrat.pit_windows && driverStrat.pit_windows.length > 0 ? (
                          <>Optimal pit window identified between laps <strong>{driverStrat.pit_windows[0].optimal_lap_range[0]} and {driverStrat.pit_windows[0].optimal_lap_range[1]}</strong>. Expected net gain: ~{driverStrat.pit_windows[0].projected_gain_seconds}s.</>
                        ) : (
                          <>No immediate pit window advantages identified.</>
                        )}
                        {' '}
                        {driverStrat.undercut_threats && driverStrat.undercut_threats.length > 0 ? (
                          <>Primary threat comes from <strong>{driverStrat.undercut_threats[0].rival}</strong> with an undercut threat score of {driverStrat.undercut_threats[0].score.toFixed(1)}/100.</>
                        ) : (
                          <>Driver is currently not facing any significant undercut threats.</>
                        )}
                      </p>

                      <h3 style={{ color: 'var(--txt-white)', marginBottom: 12 }}>Stint Analysis</h3>
                      
                      {driverStrat.stints && driverStrat.stints.map((stint: any) => {
                        const degMatch = driverStrat.deg_results?.find((d: any) => d.stint === stint.stint_number);
                        return (
                          <div key={stint.stint_number} style={{ padding: 16, background: 'var(--bg-row-alt)', borderLeft: `3px solid ${stint.compound === 'SOFT' ? 'var(--red)' : stint.compound === 'MEDIUM' ? 'var(--yellow)' : 'var(--txt-white)'}`, borderRadius: 4, marginBottom: 16 }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8 }}>
                              <strong>Stint {stint.stint_number} ({stint.compound})</strong>
                              <span style={{ color: 'var(--txt-secondary)', fontSize: 12 }}>Laps {stint.start_lap}-{stint.end_lap}</span>
                            </div>
                            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 16, fontSize: 13 }}>
                              <div>
                                <div style={{ color: 'var(--txt-secondary)', fontSize: 11 }}>AVG PACE</div>
                                <div>{stint.avg_lap_time ? stint.avg_lap_time.toFixed(3) + 's' : 'N/A'}</div>
                              </div>
                              <div>
                                <div style={{ color: 'var(--txt-secondary)', fontSize: 11 }}>TYRE AGE</div>
                                <div>{stint.tyre_life_start} &rarr; {stint.tyre_life_end} laps</div>
                              </div>
                              <div>
                                <div style={{ color: 'var(--txt-secondary)', fontSize: 11 }}>DEG RATE</div>
                                <div style={{ color: degMatch && degMatch.deg_rate_per_lap > 0.1 ? 'var(--red)' : 'var(--txt-primary)' }}>
                                  {degMatch ? `+${degMatch.deg_rate_per_lap.toFixed(3)}s / lap` : 'N/A'}
                                </div>
                              </div>
                            </div>
                            {degMatch && degMatch.predicted_cliff_lap && (
                              <div style={{ marginTop: 12, paddingTop: 12, borderTop: '1px solid var(--border-soft)', fontSize: 12, color: 'var(--txt-secondary)' }}>
                                <i>Degradation cliff predicted around lap {degMatch.predicted_cliff_lap}.</i>
                              </div>
                            )}
                          </div>
                        );
                      })}

                      <h3 style={{ color: 'var(--txt-white)', marginBottom: 12, marginTop: 32 }}>Threat Matrix</h3>
                      <ul style={{ paddingLeft: 20, marginBottom: 24 }}>
                        {driverStrat.undercut_threats && driverStrat.undercut_threats.length > 0 ? (
                          driverStrat.undercut_threats.map((threat: any, i: number) => (
                            <li key={i} style={{ marginBottom: 8 }}>
                              <strong>{threat.rival}:</strong> Threat level <span style={{ color: threat.urgency === 'act' || threat.urgency === 'critical' ? 'var(--red)' : 'var(--yellow)' }}>{threat.urgency.toUpperCase()}</span> 
                              {' '}(Score: {threat.score.toFixed(1)}). Projected loss of {threat.projected_position_loss} track position{threat.projected_position_loss !== 1 ? 's' : ''}.
                            </li>
                          ))
                        ) : (
                          <li style={{ color: 'var(--txt-secondary)' }}>No active undercut threats analyzed for this driver.</li>
                        )}
                      </ul>
                    </>
                  )}
                </div>
              </div>
            </>
          );
        })() : (
          <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <span className="t-data" style={{ color: 'var(--txt-dim)' }}>Select a report to view</span>
          </div>
        )}
      </div>

    </div>
  );
}
